import { Lead } from "./types";


export const leads: Lead[] = [
  {
    id: "1",
    company: "Northbridge Logistics",
    contactName: "Elena Vance",
    title: "VP of Operations",
    phone: "+15551230001",
    email: "elena.vance@northbridgelog.com",
    industry: "Logistics",
    employeeCount: 340,
    score: "hot",
  },
  {
    id: "2",
    company: "Cascade Fintech",
    contactName: "Marcus Reyes",
    title: "Head of Growth",
    phone: "+15551230002",
    email: "marcus@cascadefintech.io",
    industry: "Financial Services",
    employeeCount: 85,
    score: "hot",
  },
  {
    id: "3",
    company: "Fielding & Cole Architecture",
    contactName: "Priya Nair",
    title: "Managing Partner",
    phone: "+15551230003",
    email: "priya.nair@fieldingcole.com",
    industry: "Architecture",
    employeeCount: 22,
    score: "warm",
  },
  {
    id: "4",
    company: "Verdant Foods Co.",
    contactName: "Sam Okafor",
    title: "Director of Procurement",
    phone: "+15551230004",
    email: "s.okafor@verdantfoods.com",
    industry: "Food & Beverage",
    employeeCount: 510,
    score: "warm",
  },
  {
    id: "5",
    company: "Ashgrove Medical Supply",
    contactName: "Linda Park",
    title: "CEO",
    phone: "+15551230005",
    email: "lpark@ashgrovemed.com",
    industry: "Healthcare",
    employeeCount: 150,
    score: "hot",
  },
  {
    id: "6",
    company: "Hollis Legal Group",
    contactName: "Grace Odom",
    title: "Office Manager",
    phone: "+15551230006",
    industry: "Legal Services",
    employeeCount: 40,
    score: "cold",
  },
  {
    id: "7",
    company: "Ironclad Manufacturing",
    contactName: "Ben Walsh",
    title: "Plant Manager",
    phone: "+15551230007",
    email: "bwalsh@ironcladmfg.com",
    industry: "Manufacturing",
    employeeCount: 900,
    score: "warm",
  },
  {
    id: "8",
    company: "Solace Wellness Studio",
    contactName: "Tara Kim",
    title: "Founder",
    phone: "+15551230008",
    email: "tara@solacewellness.co",
    industry: "Health & Fitness",
    employeeCount: 12,
    score: "cold",
  },
];
